# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/dodo/UnrealEngine

TARGETS = \
	Trackmania-Android-DebugGame  \
	Trackmania-Android-Development  \
	Trackmania-Android-Shipping  \
	Trackmania-Linux-DebugGame  \
	Trackmania-Linux-Development  \
	Trackmania-Linux-Shipping  \
	Trackmania-LinuxArm64-DebugGame  \
	Trackmania-LinuxArm64-Development  \
	Trackmania-LinuxArm64-Shipping  \
	Trackmania \
	TrackmaniaEditor-Linux-DebugGame  \
	TrackmaniaEditor-Linux-Development  \
	TrackmaniaEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TrackmaniaEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TrackmaniaEditor-Linux-Debug


Trackmania-Android-DebugGame:
	 $(BUILD) Trackmania Android DebugGame  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-Android-Development:
	 $(BUILD) Trackmania Android Development  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-Android-Shipping:
	 $(BUILD) Trackmania Android Shipping  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-Linux-DebugGame:
	 $(BUILD) Trackmania Linux DebugGame  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-Linux-Development:
	 $(BUILD) Trackmania Linux Development  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-Linux-Shipping:
	 $(BUILD) Trackmania Linux Shipping  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-LinuxArm64-DebugGame:
	 $(BUILD) Trackmania LinuxArm64 DebugGame  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-LinuxArm64-Development:
	 $(BUILD) Trackmania LinuxArm64 Development  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania-LinuxArm64-Shipping:
	 $(BUILD) Trackmania LinuxArm64 Shipping  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

Trackmania: Trackmania-Linux-Development

TrackmaniaEditor-Linux-DebugGame:
	 $(BUILD) TrackmaniaEditor Linux DebugGame  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

TrackmaniaEditor-Linux-Development:
	 $(BUILD) TrackmaniaEditor Linux Development  -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" $(ARGS)

TrackmaniaEditor: TrackmaniaEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/dodo/Documents/Unreal Projects/Trackmania/Trackmania.uproject" -Game 

.PHONY: $(TARGETS)
